--권한 테이블
create table AUTHORITY(
	A_NO int,
	A_NAME varchar(100)
);
ALTER TABLE AUTHORITY ADD CONSTRAINT PK_AUTHORITY PRIMARY KEY(
	A_NO 
);

--회원 테이블
create table MEMBER(
	 EMAIL varchar(100),
	 A_NO int default 1,
	 NAME varchar(100),
	 NICKNAME varchar(100) unique,
	 PWD varchar(255),
	 POINT int default 0,
     APPROVAL_STATUS varchar(20) not null,
     APPROVAL_KEY varchar(20),
	 GRADE varchar(10) default 'SILVER',
     constraint MEMBER_GRADE_CK check(GRADE in ('SILVER', 'GOLD', 'DIAMOND'))
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY(
	 EMAIL 
);
ALTER TABLE MEMBER ADD CONSTRAINT FK_AUTHORITY_TO_MEMBER FOREIGN KEY(
	 A_NO 
) REFERENCES AUTHORITY(
	 A_NO 
) ON DELETE CASCADE;

--탈퇴회원 테이블
create table L_MEMBER(
	 EMAIL varchar(100),
	 NAME varchar(100),
	 NICKNAME varchar(100),
     LDATE datetime default SYSDATE()
);
ALTER TABLE L_MEMBER ADD CONSTRAINT PK_L_MEMBER PRIMARY KEY(
	 EMAIL 
);

--관리자계정 테이블
create table ADMIN(
	 NAME varchar(100),
	 PWD varchar(255) 
);
ALTER TABLE ADMIN ADD CONSTRAINT PK_ADMIN PRIMARY KEY(
	 NAME 
);

--캠핑장 테이블
create table CAMP(
	 CAMP_IDX int,
	 CAMP_NAME varchar(100),
	 ADDRESS varchar(255),
	 CAMP_TEL varchar(20),
	 SITE_NUM bigint,
	 FULL_NUM bigint,
	 PARKING bigint,
	 CONV varchar(255),
	 SEC_CONV varchar(255),
	 ETC_CONV varchar(255),
	 AGENCY_TEL varchar(20),
	 AGENCY_NAME varchar(100),
	 TOTAL_BOOKING int,
     INTRO varchar(4000),
     BBQ_FEE int default 0
);
ALTER TABLE CAMP ADD CONSTRAINT PK_CAMP PRIMARY KEY(
	 CAMP_IDX
);

--사업자 테이블
create table OWNER(
	EMAIL varchar(100),
	CAMP_IDX int,
	NAME varchar(100),
	OWNER_NUM varchar(20),
	COM_NAME varchar(100),
	COM_ADDR varchar(255),
	COM_TEL varchar(20)
);

ALTER TABLE OWNER ADD CONSTRAINT PK_OWNER PRIMARY KEY(
	 EMAIL 
);

ALTER TABLE OWNER ADD CONSTRAINT FK_CAMP_TO_OWNER FOREIGN KEY(
	 CAMP_IDX 
) REFERENCES CAMP(
	 CAMP_IDX
)ON DELETE CASCADE;

--찜 테이블
create table HEART(
	HEART_IDX int,
	EMAIL varchar(100),
	CAMP_IDX int
);

ALTER TABLE HEART ADD CONSTRAINT PK_HEART PRIMARY KEY(
	 HEART_IDX 
);

ALTER TABLE HEART ADD CONSTRAINT FK_MEMBER_TO_HEART FOREIGN KEY(
	 EMAIL
) REFERENCES MEMBER(
	 EMAIL
) ON DELETE CASCADE;

ALTER TABLE HEART ADD CONSTRAINT FK_CAMP_TO_HEART FOREIGN KEY(
	 CAMP_IDX 
) REFERENCES CAMP(
	 CAMP_IDX
) ON DELETE CASCADE;

--예약상태 테이블
create table B_STATE(
	S_NO int,
	S_NAME varchar(100)
);

ALTER TABLE B_STATE  ADD CONSTRAINT PK_B_STATE PRIMARY KEY(
	 S_NO
);

--예약 테이블
create table BOOKING(
	 IMP_UID varchar(100),
	 EMAIL varchar(100),
	 CAMP_IDX int,
     SORT_IDX int,
	 S_NO int default 1,
	 TOTAL_FEE int,
	 BDATE datetime default SYSDATE(),
     CHECK_IN datetime,
	 CHECK_OUT datetime,
	 TEL varchar(20),
	 MEMO varchar(255),
	 P_NUM bigint,
	 REVIEW_STATE char default 'F',
     constraint BOOKING_REVIEW_STATE_CK check(REVIEW_STATE in ('T', 'F')),
     NAME varchar(100),
     SERVICE_FEE int,
     USING_STATE char(1) default 'F',
     constraint BOOKING_USING_STATE_CK check(USING_STATE in ('T', 'F', 'U'))
);
ALTER TABLE BOOKING ADD CONSTRAINT PK_BOOKING PRIMARY KEY(
	 IMP_UID
);
ALTER TABLE BOOKING ADD CONSTRAINT FK_MEMBER_TO_BOOKING FOREIGN KEY(
	 EMAIL 
) REFERENCES MEMBER(
	 EMAIL 
) ON DELETE CASCADE;
ALTER TABLE BOOKING ADD CONSTRAINT FK_CAMP_TO_BOOKING FOREIGN KEY(
	 CAMP_IDX 
)REFERENCES CAMP(
	 CAMP_IDX 
) ON DELETE CASCADE;

ALTER TABLE BOOKING ADD CONSTRAINT FK_B_STATE_TO_BOOKING FOREIGN KEY(
	 S_NO 
) REFERENCES B_STATE(
	 S_NO 
) ON DELETE CASCADE;

--캠핑장 분류 테이블
create table SORT(
	SORT_IDX int,
	CAMP_IDX int,
	SORT_NAME varchar(100),
	SITE_NAME varchar(100),
	PEOPLE_NUM int,
	SITE_FEE int,
	FNAME varchar(1000),
	OFNAME varchar(1000)
);
ALTER TABLE SORT ADD CONSTRAINT PK_SORT PRIMARY KEY(
	 SORT_IDX
);

ALTER TABLE SORT ADD CONSTRAINT FK_CAMP_TO_SORT FOREIGN KEY(
	 CAMP_IDX 
)REFERENCES CAMP(
	 CAMP_IDX 
) ON DELETE CASCADE;

ALTER TABLE BOOKING ADD CONSTRAINT FK_SORT_IDX_TO_BOOKING FOREIGN KEY(
	 SORT_IDX 
) REFERENCES SORT(
	 SORT_IDX 
) ON DELETE CASCADE;

--리뷰 테이블
create table REVIEW(
	 REVIEW_IDX int,
	 CAMP_IDX int,
	 EMAIL varchar(100),
	 NICKNAME varchar(100),
	 CONTENT varchar(2000),
	 WDATE datetime default SYSDATE(),
	 STAR tinyint
);
ALTER TABLE REVIEW ADD CONSTRAINT PK_REVIEW PRIMARY KEY(
	 REVIEW_IDX 
);
ALTER TABLE REVIEW ADD CONSTRAINT FK_CAMP_TO_REVIEW FOREIGN KEY(
	 CAMP_IDX 
)REFERENCES CAMP(
	 CAMP_IDX bam
) ON DELETE CASCADE;

--이미지 테이블
create table IMG(
	 IMG_IDX int,
	 CAMP_IDX int,
	 FNAME varchar(1000),
	 OFNAME varchar(1000),
	 FSIZE int,
	 DIVISION varchar(20)
);
ALTER TABLE IMG ADD CONSTRAINT PK_IMG PRIMARY KEY(
	 IMG_IDX 
);
ALTER TABLE IMG ADD CONSTRAINT FK_CAMP_TO_IMG FOREIGN KEY(
	 CAMP_IDX 
)REFERENCES CAMP(
	 CAMP_IDX 
) ON DELETE CASCADE;

--문의상태 테이블
create table I_STATE(
	S_NO int,
	S_NAME varchar(100)
);

ALTER TABLE I_STATE ADD CONSTRAINT PK_I_STATE PRIMARY KEY(
	 S_NO 
);

--문의 테이블
create table INQUIRY(
	 INQ_IDX int,
	 EMAIL varchar(100),
	 S_NO int default '1',
	 TITLE varchar(1000),
	 OWNER_NUM varchar(20),
	 CONTENT varchar(4000),
	 WDATE datetime,
     COM_NAME varchar(100),
     COM_ADDR varchar(255),
     COM_TEL varchar(20)
);
ALTER TABLE INQUIRY ADD CONSTRAINT PK_INQUIRY PRIMARY KEY(
	 INQ_IDX 
);
ALTER TABLE INQUIRY ADD CONSTRAINT FK_MEMBER_TO_INQUIRY FOREIGN KEY(
	 EMAIL 
) REFERENCES MEMBER(
	 EMAIL 
) ON DELETE CASCADE;
ALTER TABLE INQUIRY ADD CONSTRAINT FK_I_STATE_TO_INQUIRY FOREIGN KEY(
	 S_NO 
) REFERENCES I_STATE(
	 S_NO 
) ON DELETE CASCADE;

